In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"F:\Clase_Heart\Data\heart_disease_uci.csv", index_col="id")
df

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
id,,,,,,,,,,,,,,,
1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
916,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
917,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
918,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
919,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
920,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [42]:
df['exang'].value_counts()

exang
False    528
True     337
Name: count, dtype: int64

In [41]:
df[['thal',"ca"]].head(20)

                 thal   ca
id
1        fixed defect  0.0
2              normal  3.0
3   reversable defect  2.0
4              normal  0.0
5              normal  0.0
6              normal  0.0
7              normal  2.0
8              normal  0.0
9   reversable defect  1.0
10  reversable defect  0.0
11       fixed defect  0.0
12             normal  0.0
13       fixed defect  1.0
14  reversable defect  0.0
15  reversable defect  0.0
16             normal  0.0
17  reversable defect  0.0
18             normal  0.0
19             normal  0.0
20             normal  0.0